#!/bin/bash

echo "** Building ARPACK - may take several minutes! **"
echo
cd ARPACK; make lib; cd ..

echo "** Building Spooles - may take several minutes! **"
echo
cd SPOOLES.2.2; make lib; cd ..

echo "** Building Calculix - may take several minutes! **"
echo
cd CalculiX/ccx_2.13/src/; make -f Makefile_MT; cd ../../..

# Move executable
mv CalculiX/ccx_2.13/src/ccx_2.13_MT ./; chmod 711 ccx_2.13_MT

# Cleanup files
rm -rf `find . -name "*.[oa]"`
